### ISSUE TITLE
MKS SGENl/TFT35 babystepping

### ISSUE THREAD

**Issue by hardy8** [makerbase-mks/MKS-TFT#471]
I use marlin 2.0.5.3 and all works fine, but now i made some changes and also switched to marlin 2.0.7.2. but now baby stepping doesn't work anymore, (the display freezes).
Why is this and how do i get it back working again, or is this a bug, so do I have to wait for an update?

Greetings Hardy

**Comment by mks-viva** [comment]
Hi! I suggest to use 2.0.5.3version temporarily.

**Comment by mks-viva** [comment]
I will close this issues temporarily

**Comment by hardy8** [comment]
Too bad, I had hoped that I could also use the latest versions of marlin, along with the improvements.

**Comment by mks-viva** [comment]
I am still very worried. There will be many bugs in the newly released version of marlin. For example, the function of POWER_LOSS_RECOVERY failure in 2.0.7.2 is more imperfect than 2.0.6...So, if 2.0.5 can be used stably, wait until 2.0.7.2 is resolved And then update it.

**Comment by hardy8** [comment]
Thanks ! I will wait.Regard HardyVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: mks-viva <notifications@github.com> Datum: 23-11-20  03:12  (GMT+01:00) Aan: makerbase-mks/MKS-TFT <MKS-TFT@noreply.github.com> Cc: hardy8 <hardy8@live.nl>, Author <author@noreply.github.com> Onderwerp: Re: [makerbase-mks/MKS-TFT] MKS SGENl/TFT35 babystepping (#471) 
I am still very worried. There will be many bugs in the newly released version of marlin. For example, the function of POWER_LOSS_RECOVERY failure in 2.0.7.2 is more imperfect than 2.0.6...So, if 2.0.5 can be used stably, wait until 2.0.7.2 is resolved And then update it.

**Comment by mks-viva** [comment]
We look forward to the new version of the firmware with more complete functions.

**Comment by V3nn3tj3** [comment]
Problem still exists with Marlin 2.0.7.2 and SGEN L V2. Any idea when this will be solved?
